name: Continuous Delivery

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to AWS Lambda (prod)
    runs-on: ubuntu-latest
    environment: prod

    strategy:
      matrix:
        node-version: [14.x]

    env:
      AWS_ACCESS_KEY_ID: ${{secrets.AWS_KEY}}
      AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET}}

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - name: Create env file
        run: |
          cat > .env << EOF

          EOF
      - name: Download `.serverless` state from S3
        run: aws s3 sync s3://${{secrets.SERVERLESS_STATE_S3_BUCKET}}/prod/.serverless .serverless --region us-east-1 --delete
      - run: npm run deploy
      - name: Upload `.serverless` state to S3
        run: aws s3 sync .serverless s3://${{secrets.SERVERLESS_STATE_S3_BUCKET}}/prod/.serverless --region us-east-1 --delete
